(lang dune 3.17)

(name lwt_to_eio)

(generate_opam_files true)

; (source
;  (github username/reponame))

(authors
 "Jules Aguillon <jules@j3s.fr>"
 "Nicolas Osborne <nicolas.osborne@tarides.com>")

(maintainers
 "Jules Aguillon <jules@j3s.fr>"
 "Nicolas Osborne <nicolas.osborne@tarides.com>")

; (license LICENSE)

; (documentation https://url/to/documentation)

(package
 (name lwt_to_eio)
 (synopsis "Convert your codebase from Lwt to Eio")
 (depends ocaml))
